INSERT INTO games (name, description, developer, publisher, image, price)VALUES('The Witcher 3: Wild Hunt', 'An open world action RPG following the adventures of Geralt of Rivia as he searches for Ciri across a war-torn continent.', 'CD Projekt Red', 'CD Projekt', 'the-witcher-3.jpg', 29.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Red Dead Redemption 2', 'An open world action adventure game set in the American frontier, following outlaw Arthur Morgan and the Van der Linde gang.', 'Rockstar Games', 'Rockstar Games', 'red-dead-redemption-2.jpg', 39.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Elden Ring', 'A challenging action RPG set in a vast fantasy world filled with dangerous enemies, mysterious locations and powerful bosses.', 'FromSoftware', 'Bandai Namco Entertainment', 'elden-ring.jpg', 59.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Minecraft', 'A sandbox game where players can explore, build structures, gather resources and survive in a procedurally generated world.', 'Mojang Studios', 'Mojang Studios', 'minecraft.jpg', 19.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Grand Theft Auto V', 'An open world action game set in Los Santos, where players follow the stories of three criminals involved in a series of dangerous heists.', 'Rockstar North', 'Rockstar Games', 'gta-5.jpg', 29.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Cyberpunk 2077', 'An open world RPG set in Night City, where players take the role of V, a mercenary searching for a way to achieve immortality.', 'CD Projekt Red', 'CD Projekt', 'cyberpunk-2077.jpg', 49.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('The Legend of Zelda: Breath of the Wild', 'An open world adventure game in which Link awakens in a ruined kingdom and explores a vast wilderness to recover his memories.', 'Nintendo EPD', 'Nintendo', 'zelda-breath-of-the-wild.jpg', 59.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('God of War', 'An action adventure game following Kratos and his son Atreus as they journey through the realms of Norse mythology.', 'Santa Monica Studio', 'Sony Interactive Entertainment', 'god-of-war.jpg', 39.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Hogwarts Legacy', 'An action RPG set in the wizarding world where players attend Hogwarts and discover magical secrets and ancient mysteries.', 'Avalanche Software', 'Warner Bros. Games', 'hogwarts-legacy.jpg', 49.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Baldur''s Gate 3', 'A party-based RPG featuring a deep story, tactical combat and a vast fantasy world inspired by the Dungeons and Dragons universe.', 'Larian Studios', 'Larian Studios', 'baldurs-gate-3.jpg', 59.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Hades', 'A fast-paced action roguelike in which Zagreus attempts to escape the Underworld while facing powerful enemies and gods.', 'Supergiant Games', 'Supergiant Games', 'hades.jpg', 24.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Resident Evil 4', 'A survival horror game following Leon S. Kennedy as he investigates the disappearance of the president''s daughter in a remote European village.', 'Capcom', 'Capcom', 'resident-evil-4.jpg', 39.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Hollow Knight', 'A challenging action adventure game set in a vast underground kingdom inhabited by mysterious creatures and dangerous enemies.', 'Team Cherry', 'Team Cherry', 'hollow-knight.jpg', 14.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Stardew Valley', 'A relaxing farming simulation RPG where players inherit a farm, grow crops, meet villagers and explore the surrounding world.', 'ConcernedApe', 'ConcernedApe', 'stardew-valley.jpg', 14.99);
INSERT INTO games (name, description, developer, publisher, image, price)VALUES('Portal 2', 'A first-person puzzle game where players use a portal device to solve increasingly complex challenges inside a mysterious research facility.', 'Valve', 'Valve', 'portal-2.jpg', 9.99);
INSERT INTO genres (name) VALUES ('Action');
INSERT INTO genres (name) VALUES ('Adventure');
INSERT INTO genres (name) VALUES ('Role-Playing');
INSERT INTO genres (name) VALUES ('Strategy');
INSERT INTO genres (name) VALUES ('Simulation');
INSERT INTO genres (name) VALUES ('Sports');
INSERT INTO genres (name) VALUES ('Racing');
INSERT INTO genres (name) VALUES ('Puzzle');
INSERT INTO genres (name) VALUES ('Horror');
INSERT INTO genres (name) VALUES ('Platform');
INSERT INTO genres (name) VALUES ('Shooter');
INSERT INTO genres (name) VALUES ('Fighting');
INSERT INTO genres (name) VALUES ('Survival');
INSERT INTO genres (name) VALUES ('Roguelike');
INSERT INTO genres (name) VALUES ('Open World');
INSERT INTO consoles (name, description, price) VALUES ('PlayStation 5', 'Sony home console featuring high performance, fast loading times and support for modern games with advanced graphics.', 549.99);
INSERT INTO consoles (name, description, price) VALUES ('Xbox Series X', 'Microsoft high-end console designed for powerful gaming, fast loading and high-resolution graphics.', 549.99);
INSERT INTO consoles (name, description, price) VALUES ('Xbox Series S', 'Compact Microsoft console offering digital gaming, fast loading times and access to a large library of Xbox games.', 299.99);
INSERT INTO consoles (name, description, price) VALUES ('Nintendo Switch', 'Hybrid Nintendo console that can be used as both a home console and a portable gaming device.', 299.99);
INSERT INTO consoles (name, description, price) VALUES ('Nintendo Switch OLED', 'Enhanced Nintendo Switch model featuring a larger OLED screen, improved audio and increased internal storage.', 349.99);
INSERT INTO consoles (name, description, price) VALUES ('Steam Deck', 'Portable gaming device by Valve that allows users to play a large selection of PC games on the go.', 399.99);
INSERT INTO consoles (name, description, price) VALUES ('PlayStation 4', 'Sony home console with an extensive library of games, multimedia features and support for online gaming.', 299.99);
INSERT INTO consoles (name, description, price) VALUES ('Xbox One', 'Microsoft home console offering access to a wide selection of games, multimedia applications and online services.', 249.99);
INSERT INTO consoles (name, description, price) VALUES ('Nintendo Wii U', 'Nintendo home console featuring a unique GamePad controller with an integrated touchscreen.', 199.99);
INSERT INTO consoles (name, description, price) VALUES ('Nintendo 3DS', 'Portable Nintendo console featuring stereoscopic 3D gaming, dual screens and a large library of exclusive titles.', 199.99);
INSERT INTO consoles (name, description, price) VALUES ('PlayStation 3', 'Sony home console known for its extensive game library, Blu-ray support and online gaming capabilities.', 199.99);
INSERT INTO consoles (name, description, price) VALUES ('Xbox 360', 'Microsoft home console with a large game library, online multiplayer capabilities and digital entertainment services.', 179.99);
INSERT INTO roles (name) VALUES ("ADMIN");
INSERT INTO roles (name) VALUES ("USER");
INSERT INTO users (username, password, role_id) VALUES ("daniele", "{noop}123456", 1);
INSERT INTO users (username, password, role_id) VALUES ("danieleUser", "{noop}1234567890", 2);
